service: url-shortener

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  create:
    handler: functions/create.create_short_url
    events:
      - http:
          method: post
          path: /
          public: true
          cors: true

  get:
    handler: functions/get.get_short_url
    events:
      - http:
          method: get
          path: /{id}
          public: true
          cors: true


resources:
  Resources:
    UrlShortenerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UrlShortenerTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: UrlShortenerTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: arn:aws:dynamodb:*:*:table/UrlShortenerTable
        Roles:
          - Ref: IamRoleLambdaExecution
