service: url-shortener

provider:
  name: aws
  runtime: python3.8

functions:
  create:
    handler: functions/create_short_url.post
    events:
      - http:
          method: post
          path: /
  get:
    handler: functions/get_short_url.get
    events:
      - http:
          method: get
          path: /{id}

resources:
  Resources:
    UrlShortenerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UrlShortenerTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
