AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  url-shortener-serverless-sam
  Sample SAM Template for url-shortener-serverless-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
#Globals:
#  Function:
#    Timeout: 3
#    MemorySize: 512

Resources:
  UrlShortenerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UrlShortenerTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  CreateShortUrlFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/
      Handler: create.create_short_url
      Runtime: python3.8
      Environment:
        Variables:
          TABLE_NAME: !Ref UrlShortenerTable
      Architectures:
        - x86_64
      Events:
        CreateShortUrl:
          Type: Api
          Properties:
            Path: /
            Method: post

  GetUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: get.get_short_url
      Runtime: python3.8
      Environment:
        Variables:
          TABLE_NAME: !Ref UrlShortenerTable
      Architectures:
        - x86_64
      Events:
        GetUrl:
          Type: Api
          Properties:
            Path: '/{shortUrl}'
            Method: get

Outputs:
  CreateUrlApi:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
  GetUrlApi:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{shortUrl}'

  CreateShortUrlFunction:
   Value: !GetAtt CreateShortUrlFunction.Arn
  CreateShortUrlFunctionIamRole:
    Value: !GetAtt CreateShortUrlFunctionRole.Arn
  GetUrlFunction:
   Value: !GetAtt GetUrlFunction.Arn
  GetUrlFunctionIamRole:
    Value: !GetAtt GetUrlFunctionRole.Arn
